- name: Ensure users are present
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    state: present
    groups: "{{ item.groups }}"
    password: "{{ item.password }}"
    create_home: true
  loop: "{{ users }}"

- name: Add SSH key for user
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.ssh_key }}"
  loop: "{{ users }}"
